esphome:
  name: crowpanel-advance-7-hmi
  friendly_name: CrowPanel Advance 7 HMI| ESP32-S3

packages:
  header: !include packages/header.yaml
  trains: !include packages/trains.yaml
  history: !include packages/history.yaml
  live_panel: !include packages/live_panel.yaml
  room_temp: !include packages/room_temp.yaml
  overlays: !include packages/overlays.yaml

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

psram:
  mode: octal
  speed: 80MHz

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Crowpanel-Advance-7-Hmi-Esp32-S3"
    password: "k9up9gRvf6ri"

captive_portal:

switch:
  - platform: template
    name: "Backlight Power"
    id: backlight_switch
    turn_on_action:
      - lambda: |-
          uint8_t cmd[1] = { 0 };
          id(bus_a).write(0x30, cmd, 1);
    turn_off_action:
      - lambda: |-
          uint8_t cmd[1] = { 245 };
          id(bus_a).write(0x30, cmd, 1);

spi:
  clk_pin: 1
  mosi_pin: 2

i2c:
  sda: 15
  scl: 16
  scan: true
  id: bus_a

display:
  - platform: mipi_rgb
    id: main_display
    model: custom
    init_sequence: []
    color_order: RGB
    invert_colors: true
    update_interval: never
    auto_clear_enabled: false
    dimensions:
      width: 800
      height: 480
    de_pin: 42
    hsync_pin: 40
    vsync_pin: 41
    pclk_pin: 39
    pclk_frequency: 16MHz
    hsync_pulse_width: 4
    hsync_front_porch: 8
    hsync_back_porch: 8
    vsync_pulse_width: 4
    vsync_front_porch: 8
    vsync_back_porch: 8
    data_pins:
      red: [7, 17, 18, 3, 46]
      green: [9, 10, 11, 12, 13, 14]
      blue: [21, 47, 48, 45, 38]


font:
  - file: "gfonts://Montserrat"
    id: montserrat_14_de
    size: 14
    glyphs: " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyzäöüÄÖÜß°"
  - file: "gfonts://Montserrat"
    id: montserrat_20_de
    size: 20
    glyphs: " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyzäöüÄÖÜß°"


lvgl:
  log_level: INFO
  color_depth: 16
  # Very dark slate background for the whole screen
  bg_color: 0x0B1120 
  buffer_size: 10%
  full_refresh: false
  text_font: montserrat_20